---
apiVersion: v1
kind: Pod
metadata:
  name: "echo1"
  namespace: default
  labels:
    app: "echo1"
spec:
  containers:
  - name: echo1
    image: "hashicorp/http-echo"
    args:
      - -listen=:8080
      - -text="ECHO-1"
    ports:
    - containerPort:  8080
      name:  http
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: default
spec:
  selector:
    app: echo1
  type: NodePort
  ports:
  - name: echo
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32101
